#ifndef DISPLAY_H
#define DISPLAY_H

#include "dimensions.h"

// VGA timing data
#define VGA_HORIZONAL_ACTIVE_PIXELS 640
#define VGA_HFRONT_PORCH_PIXELS 16
#define VGA_HSYNC_WIDTH_PIXELS 96
#define VGA_HBACK_PORCH_PIXELS 48
#define VGA_TOTAL_HORIZONAL_PIXELS (VGA_HORIZONAL_ACTIVE_PIXELS + VGA_HFRONT_PORCH_PIXELS + VGA_HSYNC_WIDTH_PIXELS + VGA_HBACK_PORCH_PIXELS)

#define VGA_VERTICAL_ACTIVE_LINES 480
#define VGA_VFRONT_PORCH_LINES 11
#define VGA_VSYNC_WIDTH_LINES 2
#define VGA_VBACK_PORCH_LINES 31
#define VGA_TOTAL_VERTICAL_LINES (VGA_VERTICAL_ACTIVE_LINES + VGA_VFRONT_PORCH_LINES + VGA_VSYNC_WIDTH_LINES + VGA_VBACK_PORCH_LINES)

#define PIXELS_TO_CYCLES(px) ((uint32_t) 512*(px)/VGA_TOTAL_HORIZONAL_PIXELS)
#define HSYNC_PERIOD PIXELS_TO_CYCLES(VGA_TOTAL_HORIZONAL_PIXELS)
#define HSYNC_SYNC_WIDTH PIXELS_TO_CYCLES(VGA_HSYNC_WIDTH_PIXELS)

#define VSYNC_PRESCALER 256
#define LINES_TO_TICKS(lines) (512/VSYNC_PRESCALER*(lines))
#define VSYNC_PERIOD_PRESCALED LINES_TO_TICKS(VGA_TOTAL_VERTICAL_LINES)
#define VSYNC_FRONT_PORCH_PRESCALED LINES_TO_TICKS(VGA_VFRONT_PORCH_LINES)
#define VSYNC_SYNC_PRESCALED LINES_TO_TICKS(VGA_VSYNC_WIDTH_LINES)
#define VSYNC_BACK_PORCH_PRESCALED LINES_TO_TICKS(VGA_VBACK_PORCH_LINES)

// if the rows are vertically offset (the screen appears split horizontally),
// change this by a hundred or so. (probably unnecessary)
#define VIRT_ADJUST 0

#endif
